server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///geekbang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  devtools:
    restart:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        geekbang:
          mapper: info

